repos:
  - repo: local
    hooks:
      - id: proxy-root-config
        name: Proxy to root pre-commit config
        entry: echo "Use repo root .pre-commit-config.yaml"
        language: system
        pass_filenames: false
